openapi: 3.0.1
info:
  title: Search
  description: ""
  termsOfService: https://go.microsoft.com/fwlink/?LinkId=329770
  contact:
    name: nugetvss
    email: nugetvss@microsoft.com
  license:
    name: MICROSOFT SOFTWARE LICENSE TERMS
    url: https://go.microsoft.com/fwlink/?LinkId=329770
  version: 4.1-preview
externalDocs:
  description: Team Foundation Server REST APIs
  url: https://aka.ms/azure-devops-rest-apis
servers:
- url: https://https://fabrikam-fiber-inc:8080/DefaultCollection/
security:
- accessToken: []
tags:
- name: Code Search Results
  description: Rest api for code search.
- name: Wiki Search Results
  description: REST API controller for wiki search.
- name: Work Item Search Results
  description: Rest api for work item search.
paths:
  /{collection}/{project}/_apis/search/codesearchresults:
    post:
      tags:
      - Code Search Results
      description: Provides a set of results for the search text.
      operationId: Fetch Code Search Results
      parameters:
      - name: collection
        in: path
        description: The name of the Team Foundation Server collection.
        required: true
        schema:
          type: string
      - name: project
        in: path
        description: Project ID or project name
        required: true
        schema:
          type: string
          x-ms-required: false
        x-ms-required: false
      - name: api-version
        in: query
        description: Version of the API to use.  This should be set to '4.1-preview.1'
          to use this version of the api.
        required: true
        schema:
          type: string
      requestBody:
        description: The Code Search Request.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CodeSearchRequest'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CodeSearchResponse'
      x-ms-docs-override-version: 4.1-preview.1
      x-ms-vss-resource: codeSearchResults
      x-ms-vss-method: FetchCodeSearchResults
      x-ms-preview: true
      x-ms-examples:
        ?
        : $ref: ./httpExamples/codeSearchResults/POST__CodeSearchResults-onprem.json
      x-codegen-request-body-name: body
  /{collection}/{project}/_apis/search/wikisearchresults:
    post:
      tags:
      - Wiki Search Results
      description: Provides a set of results for the search request.
      operationId: Fetch Wiki Search Results
      parameters:
      - name: collection
        in: path
        description: The name of the Team Foundation Server collection.
        required: true
        schema:
          type: string
      - name: project
        in: path
        description: Project ID or project name
        required: true
        schema:
          type: string
          x-ms-required: false
        x-ms-required: false
      - name: api-version
        in: query
        description: Version of the API to use.  This should be set to '4.1-preview.1'
          to use this version of the api.
        required: true
        schema:
          type: string
      requestBody:
        description: The Wiki Search Request.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WikiSearchRequest'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WikiSearchResponse'
      x-ms-docs-override-version: 4.1-preview.1
      x-ms-vss-resource: wikiSearchResults
      x-ms-vss-method: FetchWikiSearchResults
      x-ms-preview: true
      x-ms-examples:
        ?
        : $ref: ./httpExamples/wikiSearchResults/POST__WikiSearchResults-onprem.json
      x-codegen-request-body-name: body
  /{collection}/{project}/_apis/search/workitemsearchresults:
    post:
      tags:
      - Work Item Search Results
      description: Provides a set of results for the search text.
      operationId: Fetch Work Item Search Results
      parameters:
      - name: collection
        in: path
        description: The name of the Team Foundation Server collection.
        required: true
        schema:
          type: string
      - name: project
        in: path
        description: Project ID or project name
        required: true
        schema:
          type: string
          x-ms-required: false
        x-ms-required: false
      - name: api-version
        in: query
        description: Version of the API to use.  This should be set to '4.1-preview.1'
          to use this version of the api.
        required: true
        schema:
          type: string
      requestBody:
        description: The Work Item Search Request.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkItemSearchRequest'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkItemSearchResponse'
      x-ms-docs-override-version: 4.1-preview.1
      x-ms-vss-resource: workItemSearchResults
      x-ms-vss-method: FetchWorkItemSearchResults
      x-ms-preview: true
      x-ms-examples:
        ?
        : $ref: ./httpExamples/workItemSearchResults/POST__WorkItemSearchResults-onprem.json
      x-codegen-request-body-name: body
components:
  schemas:
    CodeResult:
      type: object
      properties:
        collection:
          $ref: '#/components/schemas/Collection'
        contentId:
          type: string
          description: ContentId of the result file.
        fileName:
          type: string
          description: Name of the result file.
        matches:
          type: object
          additionalProperties:
            type: array
            items:
              $ref: '#/components/schemas/Hit'
          description: 'Dictionary of field to hit offsets in the result file. Key
            identifies the area in which hits were found, for ex: file content/file
            name etc.'
        path:
          type: string
          description: Path at which result file is present.
        project:
          $ref: '#/components/schemas/Project'
        repository:
          $ref: '#/components/schemas/Repository'
        versions:
          type: array
          description: Versions of the result file.
          items:
            $ref: '#/components/schemas/Version'
      description: Defines the code result containing information of the searched
        files and its metadata.
    CodeSearchRequest:
      description: Defines a code search request.
      allOf:
      - $ref: '#/components/schemas/EntitySearchRequest'
    CodeSearchResponse:
      description: Defines a code search response item.
      allOf:
      - $ref: '#/components/schemas/EntitySearchResponse'
    Collection:
      type: object
      properties:
        name:
          type: string
          description: Name of the collection.
      description: Defines the details of the collection.
    EntitySearchRequest:
      type: object
      properties:
        $orderBy:
          type: array
          description: Options for sorting search results. If set to null, the results
            will be returned sorted by relevance. If more than one sort option is
            provided, the results are sorted in the order specified in the OrderBy.
          items:
            $ref: '#/components/schemas/SortOption'
        $skip:
          type: integer
          description: Number of results to be skipped.
          format: int32
        $top:
          type: integer
          description: Number of results to be returned.
          format: int32
        filters:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
          description: Filters to be applied. Set it to null if there are no filters
            to be applied.
        includeFacets:
          type: boolean
          description: Flag to opt for faceting in the result. Default behavior is
            false.
        searchText:
          type: string
          description: The search text.
      description: Base contract for search request types.
    EntitySearchResponse:
      type: object
      properties:
        facets:
          type: object
          additionalProperties:
            type: array
            items:
              $ref: '#/components/schemas/Filter'
          description: A dictionary storing an array of <code>Filter</code> object
            against each facet.
        infoCode:
          type: integer
          description: 'Numeric code indicating any additional information: 0 - Ok,
            1 - Account is being reindexed, 2 - Account indexing has not started,
            3 - Invalid Request, 4 - Prefix wildcard query not supported, 5 - MultiWords
            with code facet not supported, 6 - Account is being onboarded, 7 - Account
            is being onboarded or reindexed, 8 - Top value trimmed to maxresult allowed
            9 - Branches are being indexed, 10 - Faceting not enabled, 11 - Work items
            not accessible, Any other info code is used for internal purpose.'
          format: int32
      description: Defines the base contract for search response.
    Filter:
      type: object
      properties:
        id:
          type: string
          description: Id of the filter bucket.
        name:
          type: string
          description: Name of the filter bucket.
        resultCount:
          type: integer
          description: Count of matches in the filter bucket.
          format: int32
      description: Describes a filter bucket item representing the total matches of
        search result, name and id.
    Hit:
      type: object
      properties:
        charOffset:
          type: integer
          description: Gets or sets the start character offset of a piece of text.
          format: int32
        length:
          type: integer
          description: Gets or sets the length of a piece of text.
          format: int32
      description: Describes the position of a piece of text in a document.
    Project:
      type: object
      properties:
        id:
          type: string
          description: Id of the project.
          format: uuid
        name:
          type: string
          description: Name of the project.
      description: Defines the details of the project.
    ProjectReference:
      type: object
      properties:
        id:
          type: string
          description: ID of the project.
          format: uuid
        name:
          type: string
          description: Name of the project.
        visibility:
          type: string
          description: Visibility of the project.
      description: Defines the details of the project.
    Repository:
      type: object
      properties:
        id:
          type: string
          description: Id of the repository.
        name:
          type: string
          description: Name of the repository.
        type:
          type: string
          description: Version control type of the result file.
          enum:
          - git
          - tfvc
          - custom
          x-ms-enum:
            name: VersionControlType
            values:
            - value: git
              description: ""
            - value: tfvc
              description: ""
            - value: custom
              description: For internal use.
      description: Defines the details of the repository.
    SortOption:
      type: object
      properties:
        field:
          type: string
          description: Field name on which sorting should be done.
        sortOrder:
          type: string
          description: Order (ASC/DESC) in which the results should be sorted.
      description: Defines how to sort the result.
    Version:
      type: object
      properties:
        branchName:
          type: string
          description: Name of the branch.
        changeId:
          type: string
          description: ChangeId in the given branch associated with this match.
      description: Describes the details pertaining to a version of the result file.
    Wiki:
      type: object
      properties:
        id:
          type: string
          description: Id of the wiki.
        mappedPath:
          type: string
          description: Mapped path for the wiki.
        name:
          type: string
          description: Name of the wiki.
        version:
          type: string
          description: Version for wiki.
      description: Defines the details of wiki.
    WikiHit:
      type: object
      properties:
        fieldReferenceName:
          type: string
          description: Reference name of the highlighted field.
        highlights:
          type: array
          description: Matched/highlighted snippets of the field.
          items:
            type: string
      description: Defines the matched terms in the field of the wiki result.
    WikiResult:
      type: object
      properties:
        collection:
          $ref: '#/components/schemas/Collection'
        contentId:
          type: string
          description: ContentId of the result file.
        fileName:
          type: string
          description: Name of the result file.
        hits:
          type: array
          description: Highlighted snippets of fields that match the search request.
            The list is sorted by relevance of the snippets.
          items:
            $ref: '#/components/schemas/WikiHit'
        path:
          type: string
          description: Path at which result file is present.
        project:
          $ref: '#/components/schemas/ProjectReference'
        wiki:
          $ref: '#/components/schemas/Wiki'
      description: Defines the wiki result that matched a wiki search request.
    WikiSearchRequest:
      description: Defines a wiki search request.
      allOf:
      - $ref: '#/components/schemas/EntitySearchRequest'
    WikiSearchResponse:
      description: Defines a wiki search response item.
      allOf:
      - $ref: '#/components/schemas/EntitySearchResponse'
    WorkItemHit:
      type: object
      properties:
        fieldReferenceName:
          type: string
          description: Reference name of the highlighted field.
        highlights:
          type: array
          description: Matched/highlighted snippets of the field.
          items:
            type: string
      description: Defines the matched terms in the field of the work item result.
    WorkItemResult:
      type: object
      properties:
        fields:
          type: object
          additionalProperties:
            type: string
          description: A standard set of work item fields and their values.
        hits:
          type: array
          description: Highlighted snippets of fields that match the search request.
            The list is sorted by relevance of the snippets.
          items:
            $ref: '#/components/schemas/WorkItemHit'
        project:
          $ref: '#/components/schemas/Project'
        url:
          type: string
          description: Reference to the work item.
      description: Defines the work item result that matched a work item search request.
    WorkItemSearchRequest:
      description: Defines a work item search request.
      allOf:
      - $ref: '#/components/schemas/EntitySearchRequest'
    WorkItemSearchResponse:
      description: Defines a response item that is returned for a work item search
        request.
      allOf:
      - $ref: '#/components/schemas/EntitySearchResponse'
  parameters:
    api-Version-preview.1:
      name: api-version
      in: query
      description: Version of the API to use.  This should be set to '4.1-preview.1'
        to use this version of the api.
      required: true
      schema:
        type: string
  securitySchemes:
    accessToken:
      type: http
      description: Personal access token. Use any value for the user name and the
        token as the password.
      scheme: basic
x-ms-parameterized-host:
  hostTemplate: '{instance}'
  parameters:
  - name: instance
    description: TFS server name ({server:port})
    required: true
    type: string
    in: path
x-ms-vss-area: Search
