openapi: 3.0.1
info:
  title: Operations
  description: ""
  termsOfService: https://go.microsoft.com/fwlink/?LinkId=329770
  contact:
    name: nugetvss
    email: nugetvss@microsoft.com
  license:
    name: MICROSOFT SOFTWARE LICENSE TERMS
    url: https://go.microsoft.com/fwlink/?LinkId=329770
  version: "5.0"
externalDocs:
  description: Azure DevOps REST APIs
  url: https://aka.ms/azure-devops-rest-apis
servers:
- url: https://https://fabrikam-fiber-inc:8080/DefaultCollection/
security:
- accessToken: []
tags:
- name: Operations
  description: Operations provide a way to monitor the process of an async task.
paths:
  /{collection}/_apis/operations/{operationId}:
    get:
      tags:
      - Operations
      description: |-
        Gets an operation from the the operationId using the given pluginId.

        Some scenarios don’t require a pluginId. If a pluginId is not included in the call then just the operationId will be used to find an operation.
      operationId: Get
      parameters:
      - name: operationId
        in: path
        description: The ID for the operation.
        required: true
        schema:
          type: string
          format: uuid
      - name: collection
        in: path
        description: The name of the Azure DevOps collection.
        required: true
        schema:
          type: string
          x-ms-required: false
        x-ms-required: false
      - name: pluginId
        in: query
        description: The ID for the plugin.
        schema:
          type: string
          format: uuid
      - name: api-version
        in: query
        description: Version of the API to use.  This should be set to '5.0' to use
          this version of the api.
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Operation'
      x-ms-docs-override-version: "5.0"
      x-ms-vss-resource: operations
      x-ms-vss-method: GetOperation
components:
  schemas:
    Operation:
      description: Contains information about the progress or result of an async operation.
      allOf:
      - $ref: '#/components/schemas/OperationReference'
    OperationReference:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the operation.
          format: uuid
        pluginId:
          type: string
          description: Unique identifier for the plugin.
          format: uuid
        status:
          type: string
          description: The current status of the operation.
          enum:
          - notSet
          - queued
          - inProgress
          - cancelled
          - succeeded
          - failed
          x-ms-enum:
            name: OperationStatus
            values:
            - value: notSet
              description: The operation does not have a status set.
            - value: queued
              description: The operation has been queued.
            - value: inProgress
              description: The operation is in progress.
            - value: cancelled
              description: The operation was cancelled by the user.
            - value: succeeded
              description: The operation completed successfully.
            - value: failed
              description: The operation completed with a failure.
        url:
          type: string
          description: URL to get the full operation object.
      description: Reference for an async operation.
    OperationResultReference:
      type: object
      properties:
        resultUrl:
          type: string
          description: URL to the operation result.
      description: ""
    ReferenceLinks:
      type: object
      properties:
        links:
          type: object
          additionalProperties:
            type: object
            properties: {}
          description: The readonly view of the links.  Because Reference links are
            readonly, we only want to expose them as read only.
      description: The class to represent a collection of REST reference links.
  parameters:
    api-Version:
      name: api-version
      in: query
      description: Version of the API to use.  This should be set to '5.0' to use
        this version of the api.
      required: true
      schema:
        type: string
  securitySchemes:
    accessToken:
      type: http
      description: Personal access token. Use any value for the user name and the
        token as the password.
      scheme: basic
x-ms-parameterized-host:
  hostTemplate: '{instance}'
  parameters:
  - name: instance
    description: Azure DevOps server name ({server:port})
    required: true
    type: string
    in: path
x-ms-vss-area: Operations
