openapi: 3.0.1
info:
  title: UPackApi
  description: ""
  termsOfService: https://go.microsoft.com/fwlink/?LinkId=329770
  contact:
    name: nugetvss
    email: nugetvss@microsoft.com
  license:
    name: MICROSOFT SOFTWARE LICENSE TERMS
    url: https://go.microsoft.com/fwlink/?LinkId=329770
  version: 6.0-preview
externalDocs:
  description: Azure DevOps REST APIs
  url: https://aka.ms/azure-devops-rest-apis
servers:
- url: https://pkgs.dev.azure.com/
security:
- accessToken: []
tags:
- name: Universal
  description: Perform batch operations on packages
paths:
  /{organization}/{project}/_apis/packaging/feeds/{feedId}/upack/packages/{packageName}/versions/{packageVersion}:
    get:
      tags:
      - Universal
      description: |-
        Show information about a package version.

        The project parameter must be supplied if the feed was created in a project.
        If the feed is not associated with any project, omit the project parameter from the request.
      operationId: Universal_Get Package Version
      parameters:
      - name: organization
        in: path
        description: The name of the Azure DevOps organization.
        required: true
        schema:
          type: string
      - name: feedId
        in: path
        description: Name or ID of the feed.
        required: true
        schema:
          type: string
      - name: packageName
        in: path
        description: Name of the package.
        required: true
        schema:
          type: string
      - name: packageVersion
        in: path
        description: Version of the package.
        required: true
        schema:
          type: string
      - name: project
        in: path
        description: Project ID or project name
        required: true
        schema:
          type: string
          x-ms-required: false
        x-ms-required: false
      - name: showDeleted
        in: query
        description: True to show information for deleted versions
        schema:
          type: boolean
      - name: api-version
        in: query
        description: Version of the API to use.  This should be set to '6.0-preview.1'
          to use this version of the api.
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Package'
      security:
      - oauth2:
        - vso.packaging
      x-ms-docs-override-version: 6.0-preview.1
      x-ms-vss-resource: versions
      x-ms-vss-method: GetPackageVersion
      x-ms-preview: true
    delete:
      tags:
      - Universal
      description: |-
        Delete a package version from a feed's recycle bin.

        The project parameter must be supplied if the feed was created in a project.
        If the feed is not associated with any project, omit the project parameter from the request.
      operationId: Universal_Delete Package Version
      parameters:
      - name: organization
        in: path
        description: The name of the Azure DevOps organization.
        required: true
        schema:
          type: string
      - name: feedId
        in: path
        description: Name or ID of the feed.
        required: true
        schema:
          type: string
      - name: packageName
        in: path
        description: Name of the package.
        required: true
        schema:
          type: string
      - name: packageVersion
        in: path
        description: Version of the package.
        required: true
        schema:
          type: string
      - name: project
        in: path
        description: Project ID or project name
        required: true
        schema:
          type: string
          x-ms-required: false
        x-ms-required: false
      - name: api-version
        in: query
        description: Version of the API to use.  This should be set to '6.0-preview.1'
          to use this version of the api.
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Package'
      security:
      - oauth2:
        - vso.packaging_manage
      x-ms-docs-override-version: 6.0-preview.1
      x-ms-vss-resource: versions
      x-ms-vss-method: DeletePackageVersion
      x-ms-preview: true
    patch:
      tags:
      - Universal
      description: |-
        Update information for a package version.

        The project parameter must be supplied if the feed was created in a project.
        If the feed is not associated with any project, omit the project parameter from the request.
      operationId: Universal_Update Package Version
      parameters:
      - name: organization
        in: path
        description: The name of the Azure DevOps organization.
        required: true
        schema:
          type: string
      - name: feedId
        in: path
        description: Name or ID of the feed.
        required: true
        schema:
          type: string
      - name: packageName
        in: path
        description: Name of the package.
        required: true
        schema:
          type: string
      - name: packageVersion
        in: path
        description: Version of the package.
        required: true
        schema:
          type: string
      - name: project
        in: path
        description: Project ID or project name
        required: true
        schema:
          type: string
          x-ms-required: false
        x-ms-required: false
      - name: api-version
        in: query
        description: Version of the API to use.  This should be set to '6.0-preview.1'
          to use this version of the api.
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PackageVersionDetails'
        required: true
      responses:
        200:
          description: successful operation
          content: {}
      security:
      - oauth2:
        - vso.packaging_manage
      x-ms-docs-override-version: 6.0-preview.1
      x-ms-vss-resource: versions
      x-ms-vss-method: UpdatePackageVersion
      x-ms-preview: true
      x-codegen-request-body-name: body
  /{organization}/{project}/_apis/packaging/feeds/{feedId}/upack/RecycleBin/packages/{packageName}/versions/{packageVersion}:
    get:
      tags:
      - Universal
      description: |-
        Get information about a package version in the recycle bin.

        The project parameter must be supplied if the feed was created in a project.
        If the feed is not associated with any project, omit the project parameter from the request.
      operationId: Universal_GetPackageVersionFromRecycleBin
      parameters:
      - name: organization
        in: path
        description: The name of the Azure DevOps organization.
        required: true
        schema:
          type: string
      - name: feedId
        in: path
        description: Name or ID of the feed.
        required: true
        schema:
          type: string
      - name: packageName
        in: path
        description: Name of the package.
        required: true
        schema:
          type: string
      - name: packageVersion
        in: path
        description: Version of the package.
        required: true
        schema:
          type: string
      - name: project
        in: path
        description: Project ID or project name
        required: true
        schema:
          type: string
          x-ms-required: false
        x-ms-required: false
      - name: api-version
        in: query
        description: Version of the API to use.  This should be set to '6.0-preview.1'
          to use this version of the api.
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UPackPackageVersionDeletionState'
      security:
      - oauth2:
        - vso.packaging
      x-ms-docs-override-version: 6.0-preview.1
      x-ms-vss-resource: recycleBinVersions
      x-ms-vss-method: GetPackageVersionMetadataFromRecycleBin
      x-ms-preview: true
    delete:
      tags:
      - Universal
      description: |-
        Delete a package version from the recycle bin.

        The project parameter must be supplied if the feed was created in a project.
        If the feed is not associated with any project, omit the project parameter from the request.
      operationId: Universal_Delete Package Version From Recycle Bin
      parameters:
      - name: organization
        in: path
        description: The name of the Azure DevOps organization.
        required: true
        schema:
          type: string
      - name: feedId
        in: path
        description: Name or ID of the feed.
        required: true
        schema:
          type: string
      - name: packageName
        in: path
        description: Name of the package.
        required: true
        schema:
          type: string
      - name: packageVersion
        in: path
        description: Version of the package.
        required: true
        schema:
          type: string
      - name: project
        in: path
        description: Project ID or project name
        required: true
        schema:
          type: string
          x-ms-required: false
        x-ms-required: false
      - name: api-version
        in: query
        description: Version of the API to use.  This should be set to '6.0-preview.1'
          to use this version of the api.
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content: {}
      security:
      - oauth2:
        - vso.packaging_manage
      x-ms-docs-override-version: 6.0-preview.1
      x-ms-vss-resource: recycleBinVersions
      x-ms-vss-method: DeletePackageVersionFromRecycleBin
      x-ms-preview: true
    patch:
      tags:
      - Universal
      description: |-
        Restore a package version from the recycle bin to its associated feed.

        The project parameter must be supplied if the feed was created in a project.
        If the feed is not associated with any project, omit the project parameter from the request.
      operationId: Universal_Restore Package Version From Recycle Bin
      parameters:
      - name: organization
        in: path
        description: The name of the Azure DevOps organization.
        required: true
        schema:
          type: string
      - name: feedId
        in: path
        description: Name or ID of the feed.
        required: true
        schema:
          type: string
      - name: packageName
        in: path
        description: Name of the package.
        required: true
        schema:
          type: string
      - name: packageVersion
        in: path
        description: Version of the package.
        required: true
        schema:
          type: string
      - name: project
        in: path
        description: Project ID or project name
        required: true
        schema:
          type: string
          x-ms-required: false
        x-ms-required: false
      - name: api-version
        in: query
        description: Version of the API to use.  This should be set to '6.0-preview.1'
          to use this version of the api.
        required: true
        schema:
          type: string
      requestBody:
        description: Set the 'Deleted' property to 'false' to restore the package.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UPackRecycleBinPackageVersionDetails'
        required: true
      responses:
        200:
          description: successful operation
          content: {}
      security:
      - oauth2:
        - vso.packaging_manage
      x-ms-docs-override-version: 6.0-preview.1
      x-ms-vss-resource: recycleBinVersions
      x-ms-vss-method: RestorePackageVersionFromRecycleBin
      x-ms-preview: true
      x-codegen-request-body-name: body
components:
  schemas:
    BatchOperationData:
      type: object
      description: Do not attempt to use this type to create a new BatchOperationData.
        This type does not contain sufficient fields to create a new batch operation
        data.
    JsonPatchOperation:
      type: object
      properties:
        from:
          type: string
          description: The path to copy from for the Move/Copy operation.
        op:
          type: string
          description: The patch operation
          enum:
          - add
          - remove
          - replace
          - move
          - copy
          - test
          x-ms-enum:
            name: Operation
            values:
            - value: add
              description: ""
            - value: remove
              description: ""
            - value: replace
              description: ""
            - value: move
              description: ""
            - value: copy
              description: ""
            - value: test
              description: ""
        path:
          type: string
          description: The path for the operation. In the case of an array, a zero
            based index can be used to specify the position in the array (e.g. /biscuits/0/name).
            The "-" character can be used instead of an index to insert at the end
            of the array (e.g. /biscuits/-).
        value:
          type: object
          properties: {}
          description: The value for the operation. This is either a primitive or
            a JToken.
      description: The JSON model for a JSON Patch operation
    MinimalPackageDetails:
      type: object
      properties:
        id:
          type: string
          description: Package name.
        version:
          type: string
          description: Package version.
      description: Minimal package details required to identify a package within a
        protocol.
    Package:
      type: object
      properties:
        _links:
          $ref: '#/components/schemas/ReferenceLinks'
        deletedDate:
          type: string
          description: If and when the package was deleted.
          format: date-time
        id:
          type: string
          description: Package Id.
        name:
          type: string
          description: The display name of the package.
        permanentlyDeletedDate:
          type: string
          description: If and when the package was permanently deleted.
          format: date-time
        version:
          type: string
          description: The version of the package.
      description: Package version metadata for a Universal package
    PackageVersionDetails:
      type: object
      properties:
        views:
          $ref: '#/components/schemas/JsonPatchOperation'
      description: ""
    ReferenceLinks:
      type: object
      properties:
        links:
          type: object
          additionalProperties:
            type: object
            properties: {}
          description: The readonly view of the links.  Because Reference links are
            readonly, we only want to expose them as read only.
      description: The class to represent a collection of REST reference links.
    UPackPackagesBatchRequest:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/BatchOperationData'
        operation:
          type: string
          description: Type of operation that needs to be performed on packages.
          enum:
          - promote
          - delete
          - permanentDelete
          - restoreToFeed
          x-ms-enum:
            name: UPackBatchOperationType
            values:
            - value: promote
              description: Promote package versions to a release view. If constructing
                a UPackPackagesBatchRequest object with this type, use BatchPromoteData
                for its Data property. Not supported in the Recycle Bin.
            - value: delete
              description: Move package versions to the feed's Recycle Bin. Not supported
                in the Recycle Bin.
            - value: permanentDelete
              description: Permanently delete package versions. Only supported in
                the Recycle Bin.
            - value: restoreToFeed
              description: Restore deleted package versions to the feed. Only supported
                in the Recycle Bin.
        packages:
          type: array
          description: The packages onto which the operation will be performed.
          items:
            $ref: '#/components/schemas/MinimalPackageDetails'
      description: A batch of operations to apply to package versions.
    UPackPackageVersionDeletionState:
      type: object
      properties:
        deletedDate:
          type: string
          description: UTC date the package was deleted.
          format: date-time
        name:
          type: string
          description: Name of the package.
        version:
          type: string
          description: Version of the package.
      description: Deletion state of a Universal package.
    UPackRecycleBinPackageVersionDetails:
      type: object
      properties:
        deleted:
          type: boolean
          description: Setting to false will undo earlier deletion and restore the
            package to feed.
      description: ""
  parameters:
    api-Version-preview.1:
      name: api-version
      in: query
      description: Version of the API to use.  This should be set to '6.0-preview.1'
        to use this version of the api.
      required: true
      schema:
        type: string
  securitySchemes:
    accessToken:
      type: http
      description: Personal access token. Use any value for the user name and the
        token as the password.
      scheme: basic
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://app.vssps.visualstudio.com/oauth2/authorize&response_type=Assertion
          tokenUrl: https://app.vssps.visualstudio.com/oauth2/token?client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer&grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer
          scopes:
            vso.packaging: Grants the ability to read feeds and packages. Also grants
              the ability to search packages.
            vso.packaging_manage: Grants the ability to create, read, update, and
              delete feeds and packages.
            vso.packaging_write: Grants the ability to create and read feeds and packages.
x-ms-vss-area: UPack
x-ms-vss-resource-area-id: d397749b-f115-4027-b6dd-77a65dd10d21
